-- Supabase schema for medical fraud scoring
create table if not exists public.medical_claim_scores (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  claim_amount numeric not null,
  provider_peer_average numeric not null,
  duplicate_flag boolean not null,
  icd_cpt_mismatch boolean not null,
  time_anomaly boolean not null,
  statistical_score numeric not null,
  rule_score numeric not null,
  llm_score numeric not null,
  final_score numeric not null,
  risk_level text not null check (risk_level in ('Low', 'Medium', 'High'))
);

alter table public.medical_claim_scores enable row level security;

create policy "service_role_full_access"
  on public.medical_claim_scores
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
